### ISSUE TITLE
Create Marketplace Feature Card

### ISSUE THREAD

**Issue by romeara** [StarChart-Labs/chronicler#108]
Marketplace listing requires a "feature" (background) card with the following properties:

```
Guidelines for your feature card:
    Background image measures 965px by 482px (width x height).
    Text shows up clearly over the art.
    Background image contains a bit of texture.
    Feature card captures your brand personality.
```

Might be a good fit for the general background star-like stuff we have on the StarChart homepage?

**Comment by nickavv** [comment]
So this should just be a background that will be suitable for displaying text over, doesn't actually need any text itself?

**Comment by nickavv** [comment]
I'm not sure if you would want me to commit this feature card to this repository, or any repository in particular as it will probably be used for any StarChart marketplace apps, but here it is, just the space bg from our homepage scaled and cropped to the correct dimensions:
![github-feature-card](https://user-images.githubusercontent.com/1371666/56869758-a2fc4080-69d2-11e9-8f19-975e55acc6db.png)

**Comment by romeara** [comment]
@nickavv Looks good to me - probably best to put it in the branding repo?

**Comment by romeara** [comment]
I'll push it to branching as "marketplace-feature-card", feel free to move/edit

**Comment by romeara** [comment]
Pushed to https://github.com/StarChart-Labs/branding/blob/master/marketplace-feature-card.png
