### ISSUE TITLE
Setup AWS CloudFormation to Upload Static Homepage

### ISSUE THREAD

**Issue by romeara** [StarChart-Labs/chronicler#41]
Chronicler is going to have one UI page, the homepage - once available, setup serverless to upload it to S3 and link it to the root endpoint

**Comment by romeara** [comment]
This has multiple steps:

- @romeara Will setup serverless to create a target S3 bucket to house the homepage HTML
- @nickavv Will hopefully be able to find or make a plug-in to then upload the file to the created bucket as part of serverless deployment
- @romeara Will then try to use serverless to connect a GET root endpoint to that S3 bucket

**Comment by romeara** [comment]
@nickavv Found a thing to use in the meantime, though we'll likely want a more self-consistent solution in the future: https://www.npmjs.com/package/serverless-plugin-upload-s3

Or https://github.com/funkybob/serverless-s3-deploy
Or https://github.com/fernando-mc/serverless-finch

**Comment by nickavv** [comment]
Something to keep in mind, we need to deploy the `images` and `styles` directories as well. And these are identical for dev and prod. So the finch plugin there, for example, seems to want a whole directory to use as the upload, so to make that one work we would possibly have to duplicate the images and styles directories, which would be unfortunate.

**Comment by romeara** [comment]
Static webpage is now automated for deployment via serverless
